#!/bin/bash

# Main
cpm() {
    local chromium="/usr/bin/chromium-browser"
    local chromium_dir="${HOME}/.config/chromium"
    local data_dir="--user-data-dir=$chromium_dir/$1"
    local cache_dir="--disk-cache-dir=/tmp/chromium/cache-$1"
    local grep=/usr/bin/grep
    local pids=$(ps -ax \
		     | $grep -v grep \
		     | $grep "chromium-browser" \
		     | $grep "$1" \
		     | awk '{ print $1 }')

    kill-pid() {
	# Ensure process and children die
	for pid in $pids; do
	    [[ "${#pid}" -ne 0 ]] && kill "$pid" &
	done
    }

    # Check for already running process
    [[ "${#pids}" -ne 0 ]] && echo "$1 profile already runnin. Exiting." >&2; exit 1

    # If dir does not exist; create it. Then change to dir.
    if [[ ! -d "$chromium_dir"]]; then
	echo "$chromium_dir: does not exist. Creating it." >&2
	mkdir -p "$chromium_dir"
	cd "$chromium_dir"
    fi

    # Main function
    case "$1" in
        personal|work)
            "$chromium" "$data_dir" "$cache_dir" & wait "$!"
	    kill-pid
	    exit 0
	    ;;
	incognito)
	    "$chromium" --"$1" "$data_dir" "$cache_dir" & wait "$!"
	    rm -r "${data_dir#'--user-data-dir='}" "${cache_dir#'--disk-cache-dir='}"
	    kill-pid
	    exit 0
	    ;;
        ?|help)
	    echo
            echo "Usage: cpm <data_dir_name>"
	    echo
	    echo "<data_dir_name> is one of:"
	    echo
            echo "    personal"
            echo "    work"
            echo "    incognito"
	    echo
	    echo "Exit status is on of:"
	    echo
	    echo "    1: already running process"
	    echo "    2: could not cd to chromium directory"
	    echo "    3: exit status of this message"
	    echo
            exit 3
    esac
}

cpm "$1"
