#!/usr/bin/env bash

## grep
alias egrep='grep --color=always -E'
alias fgrep='grep --color=always -F'
alias igrep='grep --color=always -i'
alias grep='grep --color=always'
alias xzegrep='xzegrep --color=auto'
alias xzfgrep='xzfgrep --color=auto'
alias xzgrep='xzgrep --color=auto'
alias zegrep='zegrep --color=auto'
alias zfgrep='zfgrep --color=auto'
alias zgrep='zgrep --color=auto'

## ls
alias l='ls -CF --color=always --group-directories-first'
alias l.='ls -ldF.* --color=always --group-directories-first'
alias la='ls -AlF --color=always --group-directories-first --sort=extension'
alias ll='ls -lF --color=always --group-directories-first --sort=extension'
alias ls='l'
alias lz='ls -AlFZ --color=always --group-directories-first --sort=extension'
alias lal='ls -AlF --color=always --group-directories-first --sort=extension | less -R'

## source shell env files
alias srcb='source $HOME/.bashrc'
alias srca='source $HOME/.aliases'
alias srcf='source $HOME/.functions'
alias srcsp='source $HOME/.spectre'
alias srcsh='source $HOME/.sshpw'

## virtualbox
#
# $HOME/.functions
# ```
# vmanage () { 
#     /usr/bin/vboxmanage "$@"
# }
# ```

alias vmlist='vmanage list vms'
alias vmlistl='vmanage list --long vms | less'
alias vminfo='vmanage showvminfo --machinereadable'
alias vmmod='vmanage modifyvm'
alias vmclone='vmanage clonevm'
alias vmimport='vmanage import'
alias vmstart='vmanage startvm --type gui'
alias vmstarth='vmanage startvm --type headless'
alias vmhelp='vmanage --help | less'

## editors
alias vi='vim'

## Firefox User.js
#  use 'v' to edit
alias user.js='emacs .mozilla/firefox/gm15iqn0.elijah-arkenfox/user.js'
alias user-overrides.js='emacs .mozilla/firefox/gm15iqn0.elijah-arkenfox/user-overrides.js'

## rpm-ostree
alias ro='rpm-ostree'

## misc
alias mountt='mount | column -t'
alias histc='history -c'
alias ytdl='/usr/bin/youtube-dl'
alias qemu='/usr/bin/qemu-kvm'
alias tb='/usr/bin/toolbox'

