#!/usr/bin/env bash

# Source global definitions
[ -f /etc/bashrc ] && source /etc/bashrc

# Source user specific definitions
git_home="$HOME/gits/bashrc_stuff"
env_home="$git_home/env"
bin_home="$git_home/bin"

source "$env_home/functions"
source "$env_home/translate"
source "$env_home/aliases"
source "$env_home/sshpw"

# Source MasterPassword definitions
if [[ -f "$env_home/spectre" ]] && [[ -f "$bin_home/spectre" ]] && [[ -f "$bin_home/bashlib" ]]; then
    source "$env_home/spectre"
    source "$bin_home/bashlib"
    
    export SPECTRE_USERNAME=Elijah\ Thomas\ Beale
    export SPECTRE_ALGORITHM=3
    export SPECTRE_ASKPASS="$bin_home/spectre-ask"
    export SPECTRE_FORMAT=json

fi

## history variables
export HISTFILESIZE=20000
export HISTSIZE=10000
export HISTCONTROL="ignoredups:erasedups:ignorespace"
export HISTIGNORE="l[lsaz]:[bf]g:exit:history*::edit -*:source*:cd:cd -:src -*:clear:clip:gpaste-client:git-sync"

## keep shell exiting on C-d
export IGNOREEOF=1000000000

## pager variables
export PAGER='/usr/bin/less'
export LESSOPEN="|/usr/bin/lesspipe.sh %s"
export LESS='-R -s -M +Gg'
export EDITOR="/usr/bin/emacsclient"
export LESS_TERMCAP_md=$'\e[01;31m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_us=$'\e[01;32m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_so=$'\e[45;93m'
export LESS_TERMCAP_se=$'\e[0m'
export GROFF_NO_SGR=1
export MANPAGER='less -s -M +Gg'

## shell options
shopt -s histappend
shopt -s cmdhist
shopt -s autocd
shopt -s checkwinsize
shopt -s extglob

## Make sure user D-bus is accessible
export XDG_RUNTIME_DIR="/run/user/$(id -u)"

## If $HOME/bin isn't in path, include it
if ! echo $PATH | grep -q "$HOME/bin"; then
    PATH=$HOME/bin:$PATH
fi

## Emacs Stuff
#
#  emacs vterm clear screen
if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
    function clear(){
        vterm_printf "51;Evterm-clear-scrollback";
        tput clear;
    }
fi

