#!/usr/bin/env bash

export HISTFILESIZE=20000
export HISTSIZE=10000
export HISTCONTROL=ignoredups
export HISTIGNORE="&:l[lsa]:[bf]g:exit"

shopt -s histappend
shopt -s cmdhist

export IGNOREEOF=1000000000

shopt -s autocd
shopt -s checkwinsize

export LESS='-R'
export PAGER='/usr/bin/less'

# Source global definitions
if [ -f /etc/bashrc ]; then
    source /etc/bashrc
fi

# Make sure user D-bus is accessible
export XDG_RUNTIME_DIR=/run/user/$(id -u)

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=""

# export user binary directory
export PATH="${HOME}/bin:$PATH"

# Source user specific aliases and functions
if [ -f ${HOME}/.functions ]; then
    source "${HOME}/.functions"
fi

if [ -f ${HOME}/.aliases ]; then
    source "${HOME}/.aliases"
fi

if [ -f "${HOME}/.sshpw" ]; then
    source "${HOME}/.sshpw"
fi

## MasterPassword
if [ -f "${HOME}/.spectre" ] && [ -e "${HOME}/bin/spectre" ]; then
    source "${HOME}/.spectre"
    
    export SPECTRE_USERNAME=Elijah\ Thomas\ Beale
    export SPECTRE_ALGORITHM=3
    export SPECTRE_ASKPASS="${HOME}/bin/spectre_ask"
    export SPECTRE_FORMAT=json

    [[ -f "${HOME}/bin/bashlib" ]] && source "${HOME}/bin/bashlib"
fi

## Emacs Stuff
# vterm
if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
    function clear(){
        vterm_printf "51;Evterm-clear-scrollback";
        tput clear;
    }
fi

export PROMPT_COMMAND='echo -ne "\033]0;${HOSTNAME}:${PWD}\007"'
