#!/bin/bash

export HISTFILESIZE=20000
export HISTSIZE=10000
export HISTCONTROL=ignoredups
export HISTIGNORE="&:l[lsa]:[bf]g:exit"

shopt -s histappend
shopt -s cmdhist

export IGNOREEOF=1000000000

shopt -s autocd
shopt -s checkwinsize

export LESS='-R'
export PAGER='/usr/bin/less'

# Source global definitions
if [ -f /etc/bashrc ]; then
    source /etc/bashrc
fi

# Set $EDITOR to Emacs
export EDITOR='emacsclient -nw'

# Make sure user D-bus is accessible
export XDG_RUNTIME_DIR=/run/user/$(id -u)

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=""

# export user binary directory
export PATH="${HOME}/bin:$PATH"

# export path to SML/NJ binary
if [ -d "${HOME}/bin/smlnj/bin" ]; then
    export PATH="${HOME}/bin:${HOME}/bin/smlnj/bin:$PATH"
fi

# Source user specific aliases and functions
if [ -f ${HOME}/.functions ]; then
    source "${HOME}/.functions"
fi

if [ -f ${HOME}/.aliases ]; then
    source "${HOME}/.aliases"
fi

if [ -f "${HOME}/.keypass" ]; then
    source "${HOME}/.keypass"
fi

## MasterPassword
if [ -f "${HOME}/.spectre" ] && [ -e "${HOME}/bin/spectre" ]; then
    source "${HOME}/.spectre"
    
    export SPECTRE_USERNAME=Elijah\ Thomas\ Beale
    export SPECTRE_ALGORITHM=3
    export SPECTRE_ASKPASS="${HOME}/bin/spectre_ask"
    export SPECTRE_FORMAT=json
fi

if [ -f ${HOME}/bin/bashlib ]; then
    source bashlib
fi

## emacs-read-stdin
if [[ -d "${HOME}/gits/emacs-read-stdin" ]]; then
    source "${HOME}/gits/emacs-read-stdin/emacs-read-stdin.sh"
fi

# Startup commands in ${HOME}/.functions
tmux-start


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
